package com.thatsnajmul.job_sys.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;

@Entity
@Data
public class JobApplication {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Applicant-specific details
    private String applicantName;
    private String applicantEmail;
    private String applicantPhone;
    private String resumeUrl; // URL of uploaded resume/CV

    // Job-related details
    private int experience;  // Experience in years
    private double minSalary;
    private double maxSalary;
    private String coverLetter; // Updated from 'coverLater' to 'coverLetter' to match form field name

    // Job ID (for associating with a specific job post)
    private String jobId;

//    @ManyToOne
//    @JoinColumn(name = "userId")
//    @JsonBackReference // This is the child
//    private User user;

    // Getters and Setters are generated by Lombok (@Data)
}
